# Build settings
gems:
  - jemoji
  - jekyll-paginate

include:
  - _pages

# Site settings
title: "Günhan Oral"
description: > # this means to ignore newlines until "email:"
   Network & Security Engineer

email: gunhan.oral@gmail.com
#blog logo
logo: "/assets/images/gologo4.jpg"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/background_main.jpg"

name: 'Günhan Oral'
author: 'Günhan Oral'
author_image: "/assets/images/author.jpg"

paginate:	5
#highlighter: rouge

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

url: "http://gunhanoral.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@_gunhanoral'

#fill in disqus shortname to use disqus
disqus: gunhanoral

google_analytics: UA-93027736-1

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/_gunhanoral
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/gunhan.oral
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/gunhanoral
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	https://www.linkedin.com/in/gunhanoral
    desc:	Connect with me on linkedin
    share_url: https://www.linkedin.com/shareArticle
    share_title: ?title=
    share_link: "&amp;url="

pages:
  - name:       Notebooks
    url:        "{{ '/notebooks/' | prepend: site.baseurl }}"

  - name:       Slides
    url:        "{{ '/slides/' | prepend: site.baseurl }}"

  - name:       About
    url:        "{{ '/about/' | prepend: site.baseurl }}"
